### ISSUE TITLE
Unmatched asset meta found

### ISSUE THREAD

**Issue by lumixraku** [RicardoZhou/Parkour#1]
There are meta files cannot match any of the assets found in the project.
We have removed unmatched meta files from the project's assets folder, 
and backed up them to /Users/xxx/xxx/xxx/Parkour/temp/RemovedMetas.

Backed up files:
1. Scrip/Data.meta

Did something wrong here?

**Comment by RicardoZhou** [comment]
Im sorry to see it now. Just delete these files. They are invalid and i forgot to delete them. The previous version of Cocos Creator is '2.3.1', now '2.3.3'. If you want to learn the complete project, you can watch this:
[https://www.bilibili.com/video/BV19x411s7Fy](https://www.bilibili.com/video/BV19x411s7Fy)
I hope it will be useful to you.
